import {createClient} from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";

const SUPABASE_URL="https://wvgohdrjbitwdbpbzdxf.supabase.co";
const SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2Z29oZHJqYml0d2RicGJ6ZHhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY4NzA0NjQsImV4cCI6MjEwMjQ0NjQ2NH0.1mEAnwA_z5yj91QqaTwmNvFUwQ9Hb0XPOU9lfW4SvS0";
const supabase=createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
let user=null,posts=[],sort="new";
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const email=u=>u.trim().toLowerCase()+"@neodit.local";
function toast(s){$("toast").textContent=s;$("toast").style.display="block";setTimeout(()=>$("toast").style.display="none",2500)}
function modal(html){$("modalContent").innerHTML=html;$("modal").classList.remove("hidden")}
$("close").onclick=()=>$("modal").classList.add("hidden");
function authUI(){$("authArea").innerHTML=user?`<div class="auth">@${esc(user.user_metadata?.username||"user")} <button id="logout">Выйти</button></div>`:`<div class="auth"><button id="login">Войти</button><button class="primary" id="signup">Регистрация</button></div>`;if($("login"))$("login").onclick=()=>authForm("login");if($("signup"))$("signup").onclick=()=>authForm("signup");if($("logout"))$("logout").onclick=async()=>{await supabase.auth.signOut();toast("Вы вышли")}}
function authForm(mode){modal(`<h2>${mode==="login"?"Вход":"Регистрация"}</h2><div class="tabs"><button class="tab" id="alog">Войти</button><button class="tab" id="asign">Регистрация</button></div><form id="af"><div class="field"><label>Юзернейм</label><input id="un" required minlength="3" maxlength="24" pattern="[A-Za-z0-9_]+"></div><div class="field"><label>Пароль</label><input id="pw" type="password" required minlength="6"></div><div id="err" class="error"></div><button class="primary full">${mode==="login"?"Войти":"Создать аккаунт"}</button></form>`);$("alog").onclick=()=>authForm("login");$("asign").onclick=()=>authForm("signup");$("af").onsubmit=async e=>{e.preventDefault();const u=$("un").value.trim(),p=$("pw").value;if(!/^[A-Za-z0-9_]{3,24}$/.test(u))return $("err").textContent="Юзернейм: 3–24 символа, латиница, цифры и _.";try{const r=mode==="signup"?await supabase.auth.signUp({email:email(u),password:p,options:{data:{username:u}}}):await supabase.auth.signInWithPassword({email:email(u),password:p});if(r.error)throw r.error;user=r.data.user;authUI();$("modal").classList.add("hidden");toast(mode==="signup"?"Аккаунт создан":"Вы вошли");}catch(e){$("err").textContent=e.message}}}
async function load(){const r=await supabase.from("posts").select("*").order("created_at",{ascending:false});if(r.error){$("posts").innerHTML=`<div class="card">Ошибка: ${esc(r.error.message)}</div>`;return}posts=r.data||[];render()}
function render(){let a=[...posts],q=($("search").value||"").toLowerCase();if(q)a=a.filter(p=>(p.title+" "+(p.content||p.body||"")+" "+(p.community||"")).toLowerCase().includes(q));if(sort==="top")a.sort((x,y)=>(y.score||0)-(x.score||0));if(sort==="old")a.sort((x,y)=>new Date(x.created_at)-new Date(y.created_at));$("posts").innerHTML=a.length?a.map(p=>`<article class="post"><div class="votes"><button class="vote" onclick="vote(${p.id})">▲</button><div class="score">${p.score||0}</div><button class="vote" onclick="vote(${p.id})">▼</button></div><div class="body"><div class="meta">r/${esc(p.community||"general")} · ${new Date(p.created_at).toLocaleString("ru-RU")} · @${esc(p.author||"user")}</div><h2>${esc(p.title)}</h2><p>${esc(p.content||p.body||"")}</p><div class="actions"><button class="link" onclick="comments(${p.id})">💬 Комментарии</button></div></div></article>`).join(""):"<div class='card'>Постов пока нет.</div>"}
$("search").oninput=render;document.querySelectorAll(".sort").forEach(b=>b.onclick=()=>{sort=b.dataset.sort;document.querySelectorAll(".sort").forEach(x=>x.classList.toggle("active",x===b));render()});
$("createBtn").onclick=()=>{if(!user)return authForm("login");modal(`<h2>Новый пост</h2><form id="pf"><div class="field"><label>Сообщество</label><input id="com" value="general" maxlength="30"></div><div class="field"><label>Заголовок</label><input id="title" required maxlength="200"></div><div class="field"><label>Текст</label><textarea id="content" required maxlength="20000"></textarea></div><button class="primary full">Опубликовать</button></form>`);$("pf").onsubmit=async e=>{e.preventDefault();const r=await supabase.from("posts").insert({title:$("title").value.trim(),content:$("content").value.trim(),author:user.user_metadata?.username||"user",community:$("com").value.trim()||"general"});if(r.error)toast(r.error.message);else{$("modal").classList.add("hidden");await load();toast("Пост опубликован")}}};
window.comments=async id=>{const r=await supabase.from("comments").select("*").eq("post_id",id).order("created_at");if(r.error)return toast(r.error.message);modal(`<h2>Комментарии</h2>${(r.data||[]).map(c=>`<div class="card"><b>@${esc(c.author)}</b><p>${esc(c.body)}</p></div>`).join("")||"<p>Комментариев пока нет.</p>"}${user?`<form id="cf"><div class="field"><textarea id="cb" required placeholder="Комментарий..."></textarea></div><button class="primary">Отправить</button></form>`:"<p>Войдите, чтобы комментировать.</p>"}`);if(user)$("cf").onsubmit=async e=>{e.preventDefault();const x=await supabase.from("comments").insert({post_id:id,author:user.user_metadata?.username||"user",body:$("cb").value.trim()});if(x.error)toast(x.error.message);else comments(id)}};
window.vote=()=>toast("Голосование подключим после создания таблицы votes.");
(async()=>{const s=await supabase.auth.getSession();user=s.data.session?.user||null;authUI();await load();supabase.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;authUI()})})();
