-- NEODIT FINAL DATABASE
-- Запускать после удаления старых таблиц.

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique
);

create table public.posts (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles(id) on delete cascade,
  community text not null default 'general',
  title text not null,
  body text not null,
  score integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

create table public.votes (
  user_id uuid not null references auth.users(id) on delete cascade,
  post_id bigint not null references public.posts(id) on delete cascade,
  value integer not null check (value in (-1,1)),
  created_at timestamptz not null default now(),
  primary key (user_id, post_id)
);

-- Automatically create the profile when a Supabase Auth user is created.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data->>'username', ''),
      'user_' || left(replace(new.id::text, '-', ''), 8)
    )
  )
  on conflict (id) do update
    set username = excluded.username;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.votes enable row level security;

create policy "profiles read" on public.profiles for select to anon,authenticated using (true);
create policy "profiles insert own" on public.profiles for insert to authenticated with check (auth.uid()=id);
create policy "profiles update own" on public.profiles for update to authenticated using (auth.uid()=id) with check (auth.uid()=id);

create policy "posts read" on public.posts for select to anon,authenticated using (true);
create policy "posts insert auth" on public.posts for insert to authenticated with check (auth.uid()=author_id);
create policy "posts update own" on public.posts for update to authenticated using (auth.uid()=author_id) with check (auth.uid()=author_id);
create policy "posts delete own" on public.posts for delete to authenticated using (auth.uid()=author_id);

create policy "comments read" on public.comments for select to anon,authenticated using (true);
create policy "comments insert own" on public.comments for insert to authenticated with check (auth.uid()=author_id);
create policy "comments update own" on public.comments for update to authenticated using (auth.uid()=author_id) with check (auth.uid()=author_id);
create policy "comments delete own" on public.comments for delete to authenticated using (auth.uid()=author_id);

create policy "votes read own" on public.votes for select to authenticated using (auth.uid()=user_id);
create policy "votes insert own" on public.votes for insert to authenticated with check (auth.uid()=user_id);
create policy "votes update own" on public.votes for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "votes delete own" on public.votes for delete to authenticated using (auth.uid()=user_id);
